# Generated by Django 5.1.1 on 2025-01-07 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_cardoffer_back_image_cardoffer_front_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardoffer',
            name='auction_current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cardoffer',
            name='auction_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 21, 15, 4, 11, 367210, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
