# Generated by Django 5.1.1 on 2025-01-07 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_cardoffer_auction_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroffer',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cardoffer',
            name='auction_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 21, 15, 31, 55, 496931, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
