# Generated by Django 5.1.1 on 2025-01-25 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_useroffer_is_winner_alter_cardoffer_auction_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardoffer',
            name='bank_account_number',
            field=models.CharField(default='PL77124000690246321303235661', max_length=34),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardoffer',
            name='auction_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 8, 16, 37, 6, 982305, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
