# Generated by Django 5.1.1 on 2025-03-03 14:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_cardoffer_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardoffer',
            name='auction_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 17, 14, 38, 34, 17910, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.CreateModel(
            name='ShippingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=150)),
                ('house_number', models.CharField(max_length=10)),
                ('apartment_number', models.CharField(blank=True, max_length=10, null=True)),
                ('card_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='cards.cardoffer')),
            ],
        ),
    ]
