# Generated by Django 5.1.1 on 2025-03-03 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_alter_cardoffer_auction_end_date_shippingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdata',
            name='delivery_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cardoffer',
            name='auction_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 17, 14, 41, 41, 644434, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
