# Generated by Django 5.1.1 on 2025-06-11 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_shippingdata_delivery_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardoffer',
            name='auction_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 25, 13, 13, 46, 496385, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='cardoffer',
            name='bank_account_number',
            field=models.CharField(max_length=35),
        ),
    ]
