# Generated by Django 5.1.1 on 2024-12-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_verificationcode_delete_verificationcodes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=697920, max_length=6),
        ),
    ]
