# Generated by Django 5.1.1 on 2025-01-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_verified_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=206449, max_length=6),
        ),
    ]
