# Generated by Django 5.1.1 on 2025-01-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_verificationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=530155, max_length=6),
        ),
        migrations.DeleteModel(
            name='VerificationRequest',
        ),
    ]
